[ntcb]
accessKey = "ff1298d1-a3f6-4942-890b-81283034dcde"  #报文中的Access Key
authServer = "http://127.0.0.1:20000"
publisherId = "botdolly"                          #报文中的Publisher ID
componentId = "botdolly"                          #报文中的Component ID
appVersion = "1.0.0"                                #程序版本信息
appIntro = "Bot进程模版Dolly"                      #程序介绍
appAuthor = "Ntcb Team"                             #作者名称
serverNodeId = 1                                    #生成雪花ID的服务器Node的ID
reconnectDuration = 30                              #Mqtt最大重新连接时间
broker = "127.0.0.1:1883"                          #Mqtt服务器地址
brokerUser = ""                                     #Mqtt服务器用户
brokerPassword = ""                                 #Mqtt服务器用户密码
statCronPattern = "# */1 * * * *"                  #定期回报Stat消息的定时任务Pattern
autoshutdown = false                                #运行完Job是否自动退出